spring:
  application:
    name: todo-backend
  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        default_schema: todolist_db
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile

jwt:
  secret: ${JWT_SECRET}

app:
  oauth-redirect-url: ${APP_OAUTH_REDIRECT_URL}
  cors-allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
  password-reset-url: ${APP_PASSWORD_RESET_URL}
  mail-type: ${APP_MAIL_TYPE:log}

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    org.hibernate: info
